//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Verify", ReplyAction="http://tempuri.org/IService/VerifyResponse")]
        string Verify(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Verify", ReplyAction="http://tempuri.org/IService/VerifyResponse")]
        System.Threading.Tasks.Task<string> VerifyAsync(string xmlUrl, string xsdUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XPathSearch", ReplyAction="http://tempuri.org/IService/XPathSearchResponse")]
        string XPathSearch(string xml, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/XPathSearch", ReplyAction="http://tempuri.org/IService/XPathSearchResponse")]
        System.Threading.Tasks.Task<string> XPathSearchAsync(string xml, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebApplication1.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService>, WebApplication1.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Verify(string xmlUrl, string xsdUrl) {
            return base.Channel.Verify(xmlUrl, xsdUrl);
        }
        
        public System.Threading.Tasks.Task<string> VerifyAsync(string xmlUrl, string xsdUrl) {
            return base.Channel.VerifyAsync(xmlUrl, xsdUrl);
        }
        
        public string XPathSearch(string xml, string path) {
            return base.Channel.XPathSearch(xml, path);
        }
        
        public System.Threading.Tasks.Task<string> XPathSearchAsync(string xml, string path) {
            return base.Channel.XPathSearchAsync(xml, path);
        }
    }
}
